In [4]:
import tensorflow
from tensorflow import keras
from keras.layers import Input,Lambda,Dense,Flatten
from keras.models import Model
from keras.applications.vgg16 import VGG16,preprocess_input
from keras.preprocessing import image
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Sequential
import numpy
from glob import glob
import matplotlib.pyplot as pyplot
from keras.models import load_model

In [29]:
classes_list=['Acne and Rosacea Photos',
 'Atopic Dermatitis Photos',
 'Bullous Disease Photos',
 'Cellulitis Impetigo and other Bacterial Infections',
 'Herpes HPV and other STDs Photos',
 'Light Diseases and Disorders of Pigmentation',
 'Lupus and other Connective Tissue diseases',
 'Melanoma Skin Cancer Nevi and Moles',
 'Nail Fungus and other Nail Disease',
 'Poison Ivy Photos and other Contact Dermatitis',
 'Psoriasis pictures Lichen Planus and related diseases',
 'Scabies Lyme Disease and other Infestations and Bites',
 'Seborrheic Keratoses and other Benign Tumors',
 'Urticaria Hives',
 'Vasculitis Photos']
def printClassList():
    for class_name in classes_list:
        print(f"{classes_list.index(class_name)} -->  {class_name}")
printClassList()
def getClassvalue(index):
    print(classes_list[index])

0 -->  Acne and Rosacea Photos
1 -->  Atopic Dermatitis Photos
2 -->  Bullous Disease Photos
3 -->  Cellulitis Impetigo and other Bacterial Infections
4 -->  Herpes HPV and other STDs Photos
5 -->  Light Diseases and Disorders of Pigmentation
6 -->  Lupus and other Connective Tissue diseases
7 -->  Melanoma Skin Cancer Nevi and Moles
8 -->  Nail Fungus and other Nail Disease
9 -->  Poison Ivy Photos and other Contact Dermatitis
10 -->  Psoriasis pictures Lichen Planus and related diseases
11 -->  Scabies Lyme Disease and other Infestations and Bites
12 -->  Seborrheic Keratoses and other Benign Tumors
13 -->  Urticaria Hives
14 -->  Vasculitis Photos


In [6]:
IMAGE_SIZE=[224,224]
training_path='C:\\Users\\Pankaj singh\\OneDrive\\Desktop\\Python Development\\Temporary\\Artificial intelligence\\Skin_Disease_Detection\\Main_Workspace\\Try_Error_Data\\train'
testing_path='C:\\Users\\Pankaj singh\\OneDrive\\Desktop\\Python Development\\Temporary\\Artificial intelligence\\Skin_Disease_Detection\\Main_Workspace\\Try_Error_Data\\test'

In [7]:
VGG16_Architecture=VGG16(input_shape=IMAGE_SIZE+[3],weights='imagenet',include_top=False)

In [8]:
VGG16_Architecture.summary()

Model: "vgg16"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 224, 224, 3)]     0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0     

In [9]:
for layer in VGG16_Architecture.layers:
    print(layer)
    layer.trainable=False

In [10]:
folders=glob('C:\\Users\\Pankaj singh\\OneDrive\\Desktop\\Python Development\\Temporary\\Artificial intelligence\\Skin_Disease_Detection\\Main_Workspace\\Try_Error_Data\\train\*')
folders

['C:\\Users\\Pankaj singh\\OneDrive\\Desktop\\Python Development\\Temporary\\Artificial intelligence\\Skin_Disease_Detection\\Main_Workspace\\Try_Error_Data\\train\\Acne and Rosacea Photos',
 'C:\\Users\\Pankaj singh\\OneDrive\\Desktop\\Python Development\\Temporary\\Artificial intelligence\\Skin_Disease_Detection\\Main_Workspace\\Try_Error_Data\\train\\Atopic Dermatitis Photos',
 'C:\\Users\\Pankaj singh\\OneDrive\\Desktop\\Python Development\\Temporary\\Artificial intelligence\\Skin_Disease_Detection\\Main_Workspace\\Try_Error_Data\\train\\Bullous Disease Photos',
 'C:\\Users\\Pankaj singh\\OneDrive\\Desktop\\Python Development\\Temporary\\Artificial intelligence\\Skin_Disease_Detection\\Main_Workspace\\Try_Error_Data\\train\\Cellulitis Impetigo and other Bacterial Infections',
 'C:\\Users\\Pankaj singh\\OneDrive\\Desktop\\Python Development\\Temporary\\Artificial intelligence\\Skin_Disease_Detection\\Main_Workspace\\Try_Error_Data\\train\\Herpes HPV and other STDs Photos',
 'C:\\Use

In [11]:
x=Flatten()(VGG16_Architecture.output)

In [12]:
x

<KerasTensor: shape=(None, 25088) dtype=float32 (created by layer 'flatten')>

In [13]:
prediction=Dense(len(folders),activation='softmax')(x)

In [14]:
prediction

<KerasTensor: shape=(None, 15) dtype=float32 (created by layer 'dense')>

In [15]:
model=Model(inputs=VGG16_Architecture.input,outputs=prediction)

In [16]:
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 224, 224, 3)]     0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0     

In [17]:
model.compile(
    loss='categorical_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

In [18]:
train_data_generator=ImageDataGenerator(rescale=1./255,shear_range=0.2,zoom_range=0.2,horizontal_flip=True)

In [19]:
train_data_generator

In [20]:
test_data_generator=ImageDataGenerator(rescale=1./255)

In [21]:
training_set=train_data_generator.flow_from_directory(training_path,target_size=IMAGE_SIZE,batch_size=32,class_mode='categorical')

Found 9056 images belonging to 15 classes.


In [22]:
testing_set=test_data_generator.flow_from_directory(testing_path,target_size=IMAGE_SIZE,batch_size=32,class_mode='categorical')

Found 2374 images belonging to 15 classes.


In [23]:
training_set.labels

array([ 0,  0,  0, ..., 14, 14, 14])

In [24]:
len(training_set)

283

In [25]:
len(testing_set)

75

In [26]:
model.fit_generator(
    training_set,
    validation_data=testing_set,
    epochs=1,
    steps_per_epoch=len(training_set),
    validation_steps=len(testing_set),
    verbose=1
)

C:\Users\Pankaj singh\AppData\Roaming\Python\Python39\site-packages\keras\engine\training.py:1972: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  warnings.warn('`Model.fit_generator` is deprecated and '


283/283 [==============================] - 3358s 12s/step - loss: 2.4646 - accuracy: 0.3066 - val_loss: 2.2836 - val_accuracy: 0.3665


In [27]:
model.save("Predefine_Architecture_VGG16_Model_For_Trial_Data.h5")

In [28]:
image_path="C:\\Users\\Pankaj singh\\OneDrive\\Desktop\\Python Development\\Temporary\\Artificial intelligence\\Skin_Disease_Detection\\Main_Workspace\\Data\\train\\Bullous Disease Photos\\benign-familial-chronic-pemphigus-8.jpg"

In [30]:
image_data=image.load_img(image_path,target_size=IMAGE_SIZE)

In [31]:
# image_data

In [32]:
image_array=image.img_to_array(image_data)

In [33]:
# image_array

In [34]:
image_array.shape

(224, 224, 3)

In [35]:
image_array_expanded_dimansion=numpy.expand_dims(image_array,axis=0)

In [36]:
# image_array_expanded_dimansion

In [37]:
image_array_expanded_dimansion.shape

(1, 224, 224, 3)

In [38]:
preprocessed_image_data=preprocess_input(image_array_expanded_dimansion)

In [39]:
# preprocessed_image_data

In [40]:
preprocessed_image_data.shape

(1, 224, 224, 3)

In [41]:
predicted_classes=model.predict(preprocessed_image_data)

In [42]:
predicted_classes

array([[1.6274130e-33, 1.8073580e-24, 6.1976896e-18, 7.0882465e-27,
        2.7616872e-04, 6.3559198e-28, 7.3468580e-13, 1.4848394e-23,
        1.5733046e-33, 0.0000000e+00, 3.0928604e-19, 3.1306170e-13,
        9.9203828e-07, 0.0000000e+00, 9.9972290e-01]], dtype=float32)

In [43]:
predicted_classes.shape

(1, 15)

In [44]:
predicted_classes[0].shape

(15,)

In [45]:
max(predicted_classes[0])

0.9997229

In [46]:
predicted_class=list(predicted_classes[0]).index(max(predicted_classes[0]))

In [47]:
print(predicted_class)

14


In [48]:
numpy.sort(predicted_classes)

array([[0.0000000e+00, 0.0000000e+00, 1.5733046e-33, 1.6274130e-33,
        6.3559198e-28, 7.0882465e-27, 1.8073580e-24, 1.4848394e-23,
        3.0928604e-19, 6.1976896e-18, 3.1306170e-13, 7.3468580e-13,
        9.9203828e-07, 2.7616872e-04, 9.9972290e-01]], dtype=float32)

In [49]:
getClassvalue(predicted_class)

Vasculitis Photos


In [50]:
printClassList()

0 -->  Acne and Rosacea Photos
1 -->  Atopic Dermatitis Photos
2 -->  Bullous Disease Photos
3 -->  Cellulitis Impetigo and other Bacterial Infections
4 -->  Herpes HPV and other STDs Photos
5 -->  Light Diseases and Disorders of Pigmentation
6 -->  Lupus and other Connective Tissue diseases
7 -->  Melanoma Skin Cancer Nevi and Moles
8 -->  Nail Fungus and other Nail Disease
9 -->  Poison Ivy Photos and other Contact Dermatitis
10 -->  Psoriasis pictures Lichen Planus and related diseases
11 -->  Scabies Lyme Disease and other Infestations and Bites
12 -->  Seborrheic Keratoses and other Benign Tumors
13 -->  Urticaria Hives
14 -->  Vasculitis Photos
