In [79]:
import tensorflow
from tensorflow import keras
from keras.layers import Input,Lambda,Dense,Flatten
from keras.models import Model
from keras.applications.vgg16 import VGG16,preprocess_input
from keras.preprocessing import image
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Sequential
import numpy
from glob import glob
import matplotlib.pyplot as pyplot
from keras.models import load_model

In [106]:
classes_list=['Acne and Rosacea Photos','Actinic Keratosis Basal Cell Carcinoma and other Malignant Lesions','Atopic Dermatitis Photos','Bullous Disease Photos','Cellulitis Impetigo and other Bacterial Infections','Eczema Photos','Exanthems and Drug Eruptions','Hair Loss Photos Alopecia and other Hair Diseases','Herpes HPV and other STDs Photos','Light Diseases and Disorders of Pigmentation','Lupus and other Connective Tissue diseases','Melanoma Skin Cancer Nevi and Moles','Nail Fungus and other Nail Disease','Poison Ivy Photos and other Contact Dermatitis','Psoriasis pictures Lichen Planus and related diseases','Scabies Lyme Disease and other Infestations and Bites','Seborrheic Keratoses and other Benign Tumors','Systemic Disease','Tinea Ringworm Candidiasis and other Fungal Infections','Urticaria Hives','Vascular Tumors','Vasculitis Photos','Warts Molluscum and other Viral Infections']
def printClassList():
    for class_name in classes_list:
        print(f"{classes_list.index(class_name)} -->  {class_name}")
printClassList()
def getClassvalue(index):
    print(classes_list[index])

0 -->  Acne and Rosacea Photos
1 -->  Actinic Keratosis Basal Cell Carcinoma and other Malignant Lesions
2 -->  Atopic Dermatitis Photos
3 -->  Bullous Disease Photos
4 -->  Cellulitis Impetigo and other Bacterial Infections
5 -->  Eczema Photos
6 -->  Exanthems and Drug Eruptions
7 -->  Hair Loss Photos Alopecia and other Hair Diseases
8 -->  Herpes HPV and other STDs Photos
9 -->  Light Diseases and Disorders of Pigmentation
10 -->  Lupus and other Connective Tissue diseases
11 -->  Melanoma Skin Cancer Nevi and Moles
12 -->  Nail Fungus and other Nail Disease
13 -->  Poison Ivy Photos and other Contact Dermatitis
14 -->  Psoriasis pictures Lichen Planus and related diseases
15 -->  Scabies Lyme Disease and other Infestations and Bites
16 -->  Seborrheic Keratoses and other Benign Tumors
17 -->  Systemic Disease
18 -->  Tinea Ringworm Candidiasis and other Fungal Infections
19 -->  Urticaria Hives
20 -->  Vascular Tumors
21 -->  Vasculitis Photos
22 -->  Warts Molluscum and other Vir

In [71]:
IMAGE_SIZE=[224,224]
training_path='C:\\Users\\Pankaj singh\\OneDrive\\Desktop\\Python Development\\Temporary\\Artificial intelligence\\Skin_Disease_Detection\\Main_Workspace\\Data\\train'
testing_path='C:\\Users\\Pankaj singh\\OneDrive\\Desktop\\Python Development\\Temporary\\Artificial intelligence\\Skin_Disease_Detection\\Main_Workspace\\Data\\test'

In [6]:
VGG16_Architecture=VGG16(input_shape=IMAGE_SIZE+[3],weights='imagenet',include_top=False)

In [8]:
VGG16_Architecture.summary()

Model: "vgg16"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 224, 224, 3)]     0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0     

In [12]:
for layer in VGG16_Architecture.layers:
    print(layer)
    layer.trainable=False

In [51]:
folders=glob('C:\\Users\\Pankaj singh\\OneDrive\\Desktop\\Python Development\\Temporary\\Artificial intelligence\\Skin_Disease_Detection\\Main_Workspace\\Data\\train\*')
folders

['C:\\Users\\Pankaj singh\\OneDrive\\Desktop\\Python Development\\Temporary\\Artificial intelligence\\Skin_Disease_Detection\\Main_Workspace\\Data\\train\\Acne and Rosacea Photos',
 'C:\\Users\\Pankaj singh\\OneDrive\\Desktop\\Python Development\\Temporary\\Artificial intelligence\\Skin_Disease_Detection\\Main_Workspace\\Data\\train\\Actinic Keratosis Basal Cell Carcinoma and other Malignant Lesions',
 'C:\\Users\\Pankaj singh\\OneDrive\\Desktop\\Python Development\\Temporary\\Artificial intelligence\\Skin_Disease_Detection\\Main_Workspace\\Data\\train\\Atopic Dermatitis Photos',
 'C:\\Users\\Pankaj singh\\OneDrive\\Desktop\\Python Development\\Temporary\\Artificial intelligence\\Skin_Disease_Detection\\Main_Workspace\\Data\\train\\Bullous Disease Photos',
 'C:\\Users\\Pankaj singh\\OneDrive\\Desktop\\Python Development\\Temporary\\Artificial intelligence\\Skin_Disease_Detection\\Main_Workspace\\Data\\train\\Cellulitis Impetigo and other Bacterial Infections',
 'C:\\Users\\Pankaj singh

In [52]:
x=Flatten()(VGG16_Architecture.output)

In [53]:
x

<KerasTensor: shape=(None, 25088) dtype=float32 (created by layer 'flatten_1')>

In [54]:
prediction=Dense(len(folders),activation='softmax')(x)

In [55]:
prediction

<KerasTensor: shape=(None, 23) dtype=float32 (created by layer 'dense_1')>

In [56]:
model=Model(inputs=VGG16_Architecture.input,outputs=prediction)

In [57]:
model.summary()

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 224, 224, 3)]     0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0   

In [58]:
model.compile(
    loss='categorical_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

In [59]:
train_data_generator=ImageDataGenerator(rescale=1./255,shear_range=0.2,zoom_range=0.2,horizontal_flip=True)

In [60]:
train_data_generator

In [61]:
test_data_generator=ImageDataGenerator(rescale=1./255)

In [69]:
training_set=train_data_generator.flow_from_directory(training_path,target_size=IMAGE_SIZE,batch_size=32,class_mode='categorical')

Found 15557 images belonging to 23 classes.


In [72]:
testing_set=test_data_generator.flow_from_directory(testing_path,target_size=IMAGE_SIZE,batch_size=32,class_mode='categorical')

Found 4002 images belonging to 23 classes.


In [73]:
training_set.labels

array([ 0,  0,  0, ..., 22, 22, 22])

In [74]:
len(training_set)

487

In [75]:
len(testing_set)

126

In [77]:
model.fit_generator(
    training_set,
    validation_data=testing_set,
    epochs=1,
    steps_per_epoch=len(training_set),
    validation_steps=len(testing_set)
)

487/487 [==============================] - 5078s 10s/step - loss: 2.9878 - accuracy: 0.2173 - val_loss: 2.8608 - val_accuracy: 0.2621


In [78]:
model.save("Predefine_Architecture_VGG16_Model.h5")

In [167]:
image_path="C:\\Users\\Pankaj singh\\OneDrive\\Desktop\\Python Development\\Temporary\\Artificial intelligence\\Skin_Disease_Detection\\Main_Workspace\\Data\\train\\Bullous Disease Photos\\benign-familial-chronic-pemphigus-8.jpg"

In [168]:
image_data=image.load_img(image_path,target_size=IMAGE_SIZE)

In [169]:
# image_data

In [170]:
image_array=image.img_to_array(image_data)

In [171]:
# image_array

In [172]:
image_array.shape

(224, 224, 3)

In [173]:
image_array_expanded_dimansion=numpy.expand_dims(image_array,axis=0)

In [174]:
# image_array_expanded_dimansion

In [175]:
image_array_expanded_dimansion.shape

(1, 224, 224, 3)

In [176]:
preprocessed_image_data=preprocess_input(image_array_expanded_dimansion)

In [177]:
# preprocessed_image_data

In [178]:
preprocessed_image_data.shape

(1, 224, 224, 3)

In [179]:
predicted_classes=model.predict(preprocessed_image_data)

In [187]:
predicted_classes

array([[0.0000000e+00, 1.2292465e-06, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 6.3647259e-31, 0.0000000e+00, 0.0000000e+00,
        2.7140622e-22, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        1.3395725e-28, 9.9999881e-01, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 2.0686295e-36, 8.7019207e-35]], dtype=float32)

In [181]:
predicted_classes.shape

(1, 23)

In [182]:
predicted_classes[0].shape

(23,)

In [183]:
max(predicted_classes[0])

0.9999988

In [184]:
predicted_class=list(predicted_classes[0]).index(max(predicted_classes[0]))

In [185]:
print(predicted_class)

17


In [192]:
numpy.sort(predicted_classes)

array([[0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        2.0686295e-36, 8.7019207e-35, 6.3647259e-31, 1.3395725e-28,
        2.7140622e-22, 1.2292465e-06, 9.9999881e-01]], dtype=float32)

In [164]:
getClassvalue(predicted_class)

Systemic Disease
